### ISSUE TITLE
lvls

### ISSUE THREAD

**Issue by Tixfun** [quiode/TroyTD#62]
Tower upgrades als lvl angeben (1, 2, 3...)

**Comment by quiode** [comment]
![image](https://user-images.githubusercontent.com/51075975/152851800-5f07358f-0b39-4232-8fc3-686dd738828f.png)
@Tixfun so guet?

**Comment by quiode** [comment]
done in e9e623e447c2c6d7e7625121ca1c6e900f02a8a7
