### ISSUE TITLE
Upgrade cost

### ISSUE THREAD

**Issue by Tixfun** [quiode/TroyTD#65]
Upgrade cost of Unit amount and AOE count doubled

Upgrade cost goes up 20% after each upgrade

(optional upgrade cost wird angezeigt ingame)

**Comment by quiode** [comment]
>(optional upgrade cost wird angezeigt ingame)
@Tixfun wie genau sollte das genau aussehen?

**Comment by quiode** [comment]
done in 8403659836a77a8717d61edee15e754825bbb6a2...9ab549fc8505500050d895dab07964b1a2be80d2
